Fixing bug : error when using OpenSSL 3
atInisiatifZakat/template pull request #9
Opened 2024-07-29 09:09 UTC by anshour

2024-07-29 09:12 UTC, nuradiyana approved these changes
Buat file config baru om @anshour di folder config

2024-07-29 09:21 UTC, anshour commented
> Buat file config baru om @anshour di folder config

Done pak

2024-07-29 09:53 UTC, nuradiyana requested changes

2024-07-29 09:53 UTC, nuradiyana commented on config/template.php
> +    'use_arcfour_fallback' => env('USE_ARCFOUR_FALLBACK', true),
Kasih momentarily keterangan om

2024-07-30 04:46 UTC, closed without merging

2024-07-30 04:46 UTC, anshour commented
Close karena menyebabkan bug : file pdf tidak bisa dibuka